#!/bin/bash -ex

if [ -z "$XTRABACKUP_PASSWORD" ]; then
	echo "XTRABACKUP_PASSWORD not set"
	exit 1
fi

if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
	echo "MYSQL_ROOT_PASSWORD not set"
	exit 1
fi

CLUSTERCHECK_PASSWORD=$(echo "$XTRABACKUP_PASSWORD" | sha256sum | awk '{print $1;}')
QCOMM=""
CLUSTER_NAME=${CLUSTER_NAME:-cluster}

case "$1" in
	seed)
		shift 1

		# bootstrapping
		if [ ! -f /var/lib/mysql/skip-cluster-bootstrapping ]; then
			echo "Bootstrapping cluster"

			cat >/tmp/bootstrap.sql <<EOF
CREATE USER 'xtrabackup'@'localhost' IDENTIFIED BY '$XTRABACKUP_PASSWORD';
GRANT RELOAD,LOCK TABLES,REPLICATION CLIENT ON *.* TO 'xtrabackup'@'localhost';
CREATE USER 'clustercheck'@'localhost' IDENTIFIED BY '$CLUSTERCHECK_PASSWORD';
GRANT PROCESS ON *.* TO 'clustercheck'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
UPDATE mysql.user SET Password=PASSWORD('$MYSQL_ROOT_PASSWORD') WHERE User='root';
FLUSH PRIVILEGES;
SHUTDOWN;
EOF
			/usr/bin/mysqld_safe --skip-networking --console --init-file=/tmp/bootstrap.sql "$@" || (rm /tmp/bootstrap.sql; false)
			rm -f /tmp/bootstrap.sql
			touch /var/lib/mysql/skip-cluster-bootstrapping
		fi

		MYSQL_MODE_ARGS="--wsrep-new-cluster"

		echo "Starting seed node"
		;;
	node)
		if [ -z "$2" ]; then
			echo "Missing master node address"
			exit 1
		fi
		shift 2
		ADDRS="$2"
		SEP=""
		for ADDR in ${ADDRS//,/ }; do
			if expr "$ADDR" : '^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
				QCOMM+=$SEP$ADDR
			else
				QCOMM+=$SEP$(host -t A "$ADDR" | awk '{ print $4 }' | paste -sd ",")
			fi
			SEP=,
		done
		MYSQL_ARGS=
		write_cluster_config "$IPs"
		echo "Starting node, connecting to $IPs"
		;;
	*)
		echo "seed|node <othernode>,..."
		exit 1
esac

# start processes
set +e -m

function shutdown () {
	echo Shutting down
	test -s /var/run/mysql/mysqld.pid && kill -TERM $(cat /var/run/mysql/mysqld.pid)
}
trap shutdown TERM INT

/bin/galera-healthcheck -password="$CLUSTERCHECK_PASSWORD" -pidfile=/var/run/galera-healthcheck.pid -user clustercheck &
/usr/bin/mysqld_safe --console \
	$MYSQL_MODE_ARGS \
	--wsrep_cluster_name="$CLUSTER_NAME" \
	--wsrep_cluster_address="gcomm://$QCOMM" \
	--wsrep_sst_auth="xtrabackup:$XTRABACKUP_PASSWORD" \
	--default-time-zone="+00:00" \
	"$@" 2>&1 &
wait $!
RC=$?

test -s /var/run/galera-healthcheck.pid && kill $(cat /var/run/galera-healthcheck.pid)

exit $RC